// ==UserScript==
// @name         ModrinthSinicization
// @version      1.0.4
// @description  一个汉化Modrinth网页的的脚本，将 Modrinth 网站的内容翻译成中文。
// @author       YlovexLN, ForgeStove
// @match        https://modrinth.com/*
// @grant        none
// @license      GPL-3.0
// @supportURL https://github.com/ForgeStove/ModrinthSinicization/issues
// @downloadURL https://github.com/ForgeStove/ModrinthSinicization/raw/refs/heads/main/script.user.js
// @updateURL https://github.com/ForgeStove/ModrinthSinicization/raw/refs/heads/main/script.user.js
// ==/UserScript==

(function () {
    "use strict";

    // 翻译词典
    const translations = {
        "Project information":"项目信息",
        Icon:"图标",
        Name:"名称",
        URL:"地址",
        Summary:"总览",
        Visibility:"可见性",
        "Delete project":"删除项目",
        Archived:"存档",
        Unlisted:"不列出",
        "Select based on if the mod has functionality on the client side. Just because a mod works in Singleplayer doesn't mean it has actual client-side functionality.":"根据模组是否支持客户端功能进行选择。模组在单人模式下有效并不意味着它具有实际的客户端功能。",
        "Select based on if the mod has functionality on the":"根据模组是否在逻辑服务器上具有功能进行选择。请记住，单人游戏包含一个集成服务器。",
        "logical":" ",
        "server. Remember that Singleplayer contains an integrated server.":" ",
        "Public and archived projects are visible in search. Unlisted projects are published, but not visible in search or on user profiles. Private projects are only accessible by members of the project.":"公开和已归档的项目可在搜索结果中查看。未公开的项目已发布，但不会在搜索结果或用户个人资料中显示。私有项目仅供项目成员访问。",
        "Project settings":"项目设置",
        General:"通用",
        View:"视图",
        "If approved by the moderators:":"如果经版主批准：",
        "Visible in search":"在搜索中可见",
        "Visible on profile":"在个人资料中可见",
        "Visible via URL":"通过链接可见",
        "Removes your project from Modrinth's servers and search. Clicking on this will delete your project, so be extra careful!":"从 Modrinth 的服务器和搜索中删除您的项目。单击此按钮将删除您的项目，因此请格外小心！",
        "Save changes":"保存修改",
        "Featured tags":"特色标签",
        "You can feature up to 3 of your most relevant tags. Other tags may be promoted to featured if you do not select all 3.":"您最多可以展示 3 个最相关的标签。如果您未选择所有 3 个标签，则其他标签可能会被提升为精选标签。",
        "Accurate tagging is important to help people find your mod. Make sure to select all tags that apply.":"准确的标记对于帮助人们找到你的模组很重要。确保选择所有适用的标签。",
        "Select all categories that reflect the themes or function of your mod.":"选择所有反映您的模组主题或功能的类别。",
        "You can type an extended description of your mod here.":"你可以在这里输入你的 Mod 的扩展描述。",
        "The description must clearly and honestly describe the purpose and function of the project. See section 2.1 of the":"描述必须清晰、诚实地描述项目的目的和功能。有关完整要求，请参阅",
        "for the full requirements.":"的第 2.1 节。",
        "Preview":"预览",
        "Heading 1":"标题1",
        "Heading 2":"标题2",
        "Heading 3":"标题3",
        Bold:"粗体",
        Italic:"斜体",
        Strikethrough:"删除线",
        Code:"代码",
        Spoiler:"黑幕",
        "Bulleted list":"无序列表",
        "Ordered list":"有序列表",
        Quote:"引用",
        Link:"链接",
        Image:"图片",
        Video:"视频",
        "This editor supports":"此编辑器支持 ",
        "Markdown formatting":"Markdown 格式",
        "Select a license":"选择许可证",
        "License URL":"许可证链接",
        "How users are and aren't allowed to use your project.":"用户行为许可与限制",
        "The web location of the full license text. If you don't provide a link, the license text will be displayed instead.":"完整许可文本的网页地址。如果您不提供链接，将显示许可文本。",
        "It is important to choose a proper license for your mod. You may choose one from our list or provide a custom license. You may also provide a custom URL to your chosen license; otherwise, the license text will be displayed. See our":"为您的模组选择一个合适的许可证非常重要。您可以从我们的列表中选择一个，或者提供一个自定义许可证。您也可以提供您选择的许可证的自定义链接；否则，将显示许可证文本。有关更多信息，请参阅我们的",
        "licensing guide":"许可指南",
        "for more information.":" ",
        "This page shows you the analytics for your project,":"本页面显示您项目的分析数据：",
        "All Time":"所有时间",
        "Previous 30 minutes":"前 30 分钟",
        "Previous hour":"前 1 小时",
        "Previous 12 hours":"前 12 小时",
        "Previous 24 hours":"前 24 小时",
        "Today":"今天",
        "Yesterday":"昨天",
        "This week":"本周",
        "Last week":"上周",
        "Previous 7 days":"前 7 天",
        "This month":"本月",
        "Last month":"上月",
        "Previous 30 days":"前 30 天",
        "This quarter":"本季度",
        "Last quarter":"上季度",
        "This year":"今年",
        "Last year":"去年",
        "Previous year":"前年",
        "Previous two years":"前两年",
        "Views":"访问量",
        "Downloads by region":"按地区分布的下载量",
        "China":"中国",
        "Other":"其他",
        "United States":"美国",
        "Germany":"德国",
        "Russia":"俄罗斯",
        "France":"法国",
        "United Kingdom":"英国",
        "Hong Kong SAR":"香港特别行政区",
        "Japan":"日本",
        "Australia":"澳大利亚",
        "Canada":"加拿大",
        "Brazil":"巴西",
        "Poland":"波兰",
        "Taiwan":"台湾",
        "Netherlands":"荷兰",
        "New Zealand":"新西兰",
        "Belgium":"比利时",
        "Spain":"西班牙",
        "Czechia":"捷克",
        "Ukraine":"乌克兰",
        "Italy":"意大利",
        "Chile":"智利",
        "Toggle project colors":"切换项目颜色",
        "Download this data as CSV":"以 CSV 格式下载此数据",
        "Refresh the chart":"刷新图表",
        "Upload an image":"上传图片",
        "Click to choose an image or drag one onto this page":"单击以选择图像或将图像拖动到此页面上",
        "Upload a version":"上传版本",
        "Click to choose a file or drag one onto this page":"单击以选择文件或将文件拖动到此页面上",
        "Platform":"平台",
        "Host your next server with Modrinth Servers":"使用 Modrinth 服务器托管您的下一个服务器",
        "Modrinth Servers is the easiest way to host your own Minecraft server. Seamlessly install and play your favorite mods and modpacks, all within the Modrinth platform.":"Modrinth 服务器是托管您自己的 Minecraft 服务器的最简单方法。无缝安装和游玩您最喜欢的模组和整合包，所有这些都在 Modrinth 平台内完成。",
        "Start your server":"启动您的服务器",
        "Small":"小",
        "Large":"大",
        "Start your server on Modrinth":"在 Modrinth 上启动您的服务器",
        "There's a plan for everyone! Choose the one that fits your needs.":"总有一款适合您！选择最符合您需求的方案。",
        "Perfect for vanilla multiplayer, small friend groups, SMPs, and light modding.":"适合原版多人游戏、小型好友联机、生存多人服务器（SMP）以及轻度模组玩法。",
        "Great for modded multiplayer and small communities.":"适合模组联机和小型社群。",
        "Ideal for larger communities, modpacks, and heavy modding.":"适合大型社区、整合包和重度模组玩法。",
        "Get Started":"立即体验",
        "Build your own":"自定义你的服务器",
        "If you're a more technical server administrator, you can pick your own RAM and storage options.":"如果您是更专业的服务器管理员，您可以选择自己的内存和存储配置。",
        "Subscribe to Modrinth Servers!":"订阅 Modrinth 服务器！",
        "Configure":"配置",
        "server":"服务器",
        "Billing":"计费",
        "interval":"周期",
        "Payment":"付款",
        "Review":"审查",
        "You can change these settings later in your server options.":"您可以稍后在服务器选项中更改这些设置。",
        "Configure your server":"配置您的服务器",
        "Shared CPUs":"共享 CPU 数",
        "Max Burst CPUs":"最大突发 CPU 数",
        "Storage and shared CPU count are currently not configurable independently, and are based on the amount of RAM you select.":"存储空间和共享CPU核心数当前无法单独配置，其规格将根据您选择的内存容量自动分配。",
        "CPU bursting allows your server to temporarily use additional threads to help mitigate TPS spikes. See Modrinth Servers FAQ for more info.":"CPU 突发性能允许您的服务器临时使用额外线程，以帮助缓解 TPS 峰值波动。更多信息请参阅 Modrinth 服务器常见问题解答。",
        "This might not be powerful enough for your Minecraft server.":"当前配置可能无法满足您的 Minecraft 服务器性能需求。",
        "Configure your RAM":"配置你的内存",
        "Checking availability...":"正在检查可用性...",
        "Choose billing interval":"选择计费周期",
        "yearly":"每年",
        "monthly":"每月",
        "/ yearly":"/ 每年",
        "/ monthly":"/ 每月",
        "Final price and currency will be based on your selected payment method.":"最终价格与货币将根据您选择的支付方式确定。",
        "Total":"总计",
        "An error occurred":"发生了一个错误",
        "Dismiss":"忽略",
        "Copy to clipboard":"复制到剪贴板",
        "Frequently Asked Questions":"常见问题解答",
        "What kind of CPUs do Modrinth Servers run on?":"Modrinth 服务器在什么样的 CPU 上运行？",
        "Modrinth Servers are powered by AMD Ryzen 7900 and 7950X3D equivalent CPUs at 5+ GHz, paired with DDR5 memory.":"Modrinth 服务器由 AMD Ryzen 7900 和 7950X3D 相当的 CPU 驱动，主频为 5+ GHz，搭配 DDR5 内存。",
        "How do CPU burst threads work?":"CPU 突发线程是如何工作的？",
        "When your server is under heavy load, we temporarily give it access to additional CPU threads to help mitigate lag spikes and instability. This helps prevent the TPS from going below 20, ensuring the smoothest experience possible. Since those extra CPU threads are only shortly available during high load periods, they might not show up in Spark reports or other profiling tools.":"当您的服务器负载过重时，我们会暂时允许它访问额外的 CPU 线程，以帮助缓解延迟峰值和不稳定情况。这有助于防止 TPS 低于 20，从而确保尽可能流畅的体验。由于这些额外的 CPU 线程仅在高负载期间短暂可用，因此它们可能不会显示在 Spark 报告或其他分析工具中。",
        "Do Modrinth Servers have DDoS protection?":"Modrinth 服务器有 DDoS 保护吗？",
        "Yes. All Modrinth Servers come with DDoS protection powered by":"是的，所有 Modrinth 服务器都带有由 ",
        "which has over 17Tbps capacity. Your server is safe on Modrinth.":" 提供支持的 DDoS 保护，该基础设施的容量超过 17Tbps。您的服务器在 Modrinth 上是安全的。",
        "Where are Modrinth Servers located? Can I choose a region?":"Modrinth 服务器位于哪里？我可以选择地区吗？",
        "Currently, Modrinth Servers are located on the east coast of the United States in Vint Hill, Virginia. More regions to come in the future!":"目前，Modrinth 服务器位于美国弗吉尼亚州的温特希尔东海岸。未来还将有更多地区上线！",
        "Can I increase the storage on my server?":"我可以增加服务器上的存储空间吗？",
        "Yes, storage can be increased on your server at no additional cost. If you need more storage, reach out to Modrinth Support.":"是的，您可以在服务器上免费增加存储空间。如果您需要更多存储空间，请联系 Modrinth 支持。",
        "How fast are Modrinth Servers?":"Modrinth 服务器有多快？",
        "Modrinth Servers are hosted on very modern high-performance hardware, but it's tough to say how exactly that will translate into how fast your server will run because there are so many factors that affect it, such as the mods, data packs, or plugins you're running on your server, and even user behavior.":"Modrinth 服务器托管在现代高性能硬件上，但很难说这如何精确地转化为您的服务器运行速度，因为有许多因素会影响它，例如您在服务器上运行的模组、数据包或插件，甚至用户行为。",
        "Most performance issues that arise tend to be the fault of an unoptimized modpack, mod, data pack, or plugin that causes the server to lag. Since our servers are very high-end, you shouldn't run into much trouble as long as you pick an appropriate plan for the content you're running on the server.":"大多数性能问题通常是由未优化的整合包、模组、数据包或插件引起的，导致服务器卡顿。由于我们的服务器非常高端，只要您为服务器上运行的内容选择了合适的计划，就不应该遇到太多问题。",
        "What currency are the prices in?":"这些价格用什么货币计价？",
        "All prices are listed in United States Dollars (USD).":"所有价格均以美元 （USD） 列出。",
        "Comes with all the features you need.":"附带您需要的所有功能。",
        "Included with every server is a suite of features designed to provide a hosting experience that only Modrinth can offer.":"每台服务器都附带了一套功能，旨在提供 Modrinth 才能提供的托管体验。",
        "Custom URL":"自定义链接",
        "Backups included":"包含备份",
        "Every server comes with 15 backups stored securely off-site.":"每台服务器都带有 15 个安全存储在异地的备份。",
        "Easy to use file manager":"易于使用的文件管理器",
        "Search, manage, edit, and upload files directly to your server with ease.":"轻松搜索、管理、编辑和上传文件到您的服务器。",
        "A powerful console, server properties manager, and more":"一个强大的控制台，服务器属性管理器，以及其他功能",
        "Modrinth Servers come with powerful tools to manage your server.":"Modrinth 服务器带有强大的工具来管理您的服务器。",
        "Help when you need it":"在您需要时提供帮助",
        "Reach out to the Modrinth team for help with your server at any time.":"随时联系 Modrinth 团队以获取有关您的服务器的帮助。",
        "SFTP access":"SFTP 访问",
        "Access your server files directly with SFTP built into Modrinth Servers.":"通过 Modrinth 服务器内置的 SFTP 直接访问您的服务器文件。",
        "Advanced networking management":"高级网络管理",
        "Add your own domain to your server, reserve up to 15 ports for mods that require them, and more.":"将您自己的域名添加到您的服务器，为需要它们的模组预留最多 15 个端口，以及更多。",
        "Find a modpack. Now it's a server.":"找到一个整合包。现在它是一个服务器。",
        "Choose from the thousands of modpacks on Modrinth or create your own. Invite your friends when you're ready to play.":"从 Modrinth 上的数千个整合包中选择，或者创建你自己的。准备好玩游戏时邀请你的朋友。",
        "Play where your mods are":"在你查找模组的地方游玩",
        "Modrinth Servers seamlessly integrates the mod and modpack installation process into your server.":"Modrinth 服务器无缝集成了模组和整合包的安装过程。",
        "All your favorite mods":"所有你最喜欢的模组",
        "Choose between Vanilla, Fabric, Forge, Quilt and NeoForge. If it's on Modrinth, it can run on your server.":"在 Vanilla、Fabric、Forge、Quilt 和 NeoForge 之间进行选择。如果它在 Modrinth 上，它可以在您的服务器上运行。",
        "Manage it all on Modrinth":"在 Modrinth 上管理所有内容",
        "Your server, mods, players, and more are all on Modrinth. No need to switch between platforms.":"您的服务器、模组、玩家以及更多内容都在 Modrinth 上。无需在平台之间切换。",
        "Experience modern, reliable hosting":"体验现代、可靠的托管服务",
        "Consistently fast":"始终如一的快速",
        "Our infrastructure is never overloaded, meaning each server hosted with Modrinth always runs at its full performance.":"我们的基础设施永远不会过载，这意味着使用 Modrinth 托管的每台服务器始终以最佳性能运行。",
        "Download Modrinth":"下载 Modrinth",
        "App for Windows":"适用于 Windows 的应用程序",
        "The Modrinth App is a unique, open source launcher that allows you to play your favorite mods, and keep them up to date, all in one neat little package.":"Modrinth 应用程序是一个独特的开源启动器，可让您播放自己喜欢的模组，并使它们保持最新状态，所有这些都在一个简洁的小包中。",
        "Download the Modrinth App":"下载 Modrinth 应用程序",
        "More Download Options":"更多下载选项",
        "Unlike any launcher":"不同于任何",
        "you've used before":"你使用过的启动器",
        "Installed mods":"已安装的模组",
        "Mod management":"模组管理",
        "Modrinth makes it easy to manage all your mods in one place. You can install, uninstall, and update mods with a single click.":"Modrinth 让您能够在一个地方轻松管理所有您的模组。您可以通过单击来安装、卸载和更新模组。",
        "Share Modpacks":"分享整合包",
        "Build, share, and play modpacks with any of the thousands of mods and modpacks hosted here on Modrinth.":"在此构建、分享和游玩 Modrinth 上托管的上千种模组和整合包。",
        "Activity monitor":"任务管理器",
        "Performant":"高性能",
        "The Modrinth App performs better than many of the leading mod managers, using just 150mb of RAM!":"Modrinth 应用比许多领先的模组管理器表现更好，仅使用 150MB 的内存！",
        "Play with your favorite mods":"游玩你喜欢的模组",
        "Use the Modrinth App to download and play with your favorite mods and modpacks.":"使用 Modrinth 应用程序下载和体验你喜欢的模组和整合包。",
        "Website Integration":"网站集成",
        "The Modrinth App is fully integrated with the website, so you can access all your favorite projects from the app!":"Modrinth 应用程序与网站完全集成，因此您可以从应用程序访问所有您喜爱的项目！",
        "Modrinth’s launcher is fully open source. You can view the source code on our":"Modrinth 的启动器是完全开源的。您可以在我们的 Github 上查看源代码: ",
        "Privacy Policy.":"隐私政策。",
        "Offline mode":"离线模式",
        "Follow projects":"关注项目",
        "Play your mods, whether you are connected to the internet, or not.":"游玩您的模组，无论您是否连接到互联网。",
        "Save content you love and receive updates with one click.":"保存您喜爱的内容，一键获取更新。",
        "Our desktop app is available across all platforms,":"我们的桌面应用程序可在所有平台上使用，",
        "choose your desired version.":"选择您所需的版本。",
        "By downloading the Modrinth App you agree to our":"下载 Modrinth 应用即表示您同意我们的",
        "and":"和",
        "You can edit multiple projects at once by selecting them below.":"您可以通过下方选择来同时编辑多个项目。",
        "Edit links":"编辑链接",
        "Sort by":"排序方式",
        "Type":"类型",
        "Under review":"审核中",
        "Manage members":"管理成员",
        "Enter the Modrinth username of the person you'd like to invite to be a member of this project.":"输入您要邀请成为此项目成员的人员的 Modrinth 用户名。",
        "Leave project":"离开项目",
        "Remove yourself as a member of this project.":"将您从该项目中移除。",
        "The title of the role that this member plays for this project.":"该成员在此项目中的角色名称。",
        "Monetization weight":"变现权重",
        "Relative to all other members' monetization weights, this determines what portion of this project's revenue goes to this member.":"相对于所有其他成员的变现权重，这决定了该项目收入的哪一部分归该成员所有。",
        "This project is not managed by an organization. If you are the member of any organizations, you can transfer management to one of them.":"此项目不由任何组织管理。如果您是任何组织的成员，您可以将管理权转移给其中之一。",
        "Transfer management":"转移管理",
        "Select option":"选择选项",
        "External links":"外部链接",
        "Issue tracker":"问题追踪",
        "A place for users to report bugs, issues, and concerns about your project.":"用户可在此提交项目相关的错误报告、问题及反馈。",
        "Wiki page":"Wiki 页面",
        "A page containing information, documentation, and help for the project.":"包含项目信息、文档和帮助内容的页面",
        "Enter a valid URL":"输入有效的URL",
        "Source code":"源代码",
        "A page/repository containing the source code for your project":"项目源代码的存储库页面",
        "Discord invite":"Discord邀请链接",
        "An invitation link to your Discord server.":"Discord服务器的邀请链接",
        "Donation links":"捐赠链接",
        "Add donation links for users to support you directly.":"添加捐赠链接以便用户直接支持您",
        "Install with Modrinth App":"使用 Modrinth 应用安装",
        "Curated by":"编辑整理自",
        "Collection":"集合",
        "You don't have any servers yet!":"您还没有任何服务器！",
        "Modrinth Servers is a new way to play modded Minecraft with your friends.":"Modrinth 服务器是一种与朋友一起玩 Minecraft 的新方式。",
        "Create a Server":"创建一个服务器",
        "Edit token":"编辑令牌",
        "Revoke token":"撤销令牌",
        "PATs can be used to access Modrinth's API. For more information, see":"PAT 可用于访问 Modrinth 的 API。有关更多信息，请参阅 ",
        "Modrinth's API documentation":"Modrinth 的 API 文档",
        ". They can be created and revoked at any time.":"。可以随时创建和撤销它们。",
        "Subscribe":"订阅",
        "Your profile information is publicly viewable on Modrinth and through the":"您的个人资料信息可在 Modrinth 上公开查看，也可以通过 ",
        "Current session":"当前会话",
        "Revoke session":"撤销会话",
        "Past charges":"过去的费用",
        "All of your past charges to your Modrinth account will be listed here:":"您过去在 Modrinth 账户的所有费用将在此处列出：",
        "Applications can be used to authenticate Modrinth's users with your products. For more information, see":"应用程序可用于使用您的产品对 Modrinth 的用户进行身份验证。有关更多信息，请参阅 ",
        "Available now":"现已可用",
        "Total pending":"总待处理",
        "California Privacy Notice":"加利福尼亚州隐私声明",
        "Rewards Program Terms":"奖励计划条款",
        "Rewards Program Info":"奖励计划信息",
        "Withdraw":"提现",
        "View transfer history":"查看转账历史",
        "Available soon":"即将可用",
        "Payout methods":"收款方式",
        "Connect your PayPal account to enable withdrawing to your PayPal balance.":"将您的 PayPal 账户连接起来，以使您能够提取到您的 PayPal 余额。",
        "Tremendous payments are sent to your Modrinth email. To change/set your Modrinth email, visit":"Tremendous 支付的款项将发送至您的 Modrinth 邮箱。如需修改/设置邮箱，请",
        "Enter your Venmo username below to enable withdrawing to your Venmo balance.":"请在下方输入您的 Venmo 用户名，以便提现至 Venmo 余额。",
        "Save information":"保存信息",
        "Sign in with PayPal":"使用 PayPal 登录",
        "By uploading projects to Modrinth and withdrawing money from your account, you agree to the":"通过向 Modrinth 上传项目及从账户提现，即表示您同意",
        ". For more information on how the rewards system works, see our information page":"。有关奖励制度的详细说明，请参阅",
        "here":"此处",
        "Click to read about how Modrinth handles your revenue.":"点击查阅 Modrinth 收益处理政策",
        "Rewards Program Information":"奖励计划信息",
        "Rewards Distribution":"奖励分配",
        "Economics":"经济",
        "Relationship":"关系",
        "Disclaimer Regarding Rewards Program":"关于奖励计划的免责声明",
        "Limitation of Liability":"责任限制",
        "Governing Law":"适用法律",
        "Termination":"终止",
        "Privacy Notice for California Residents":"加利福尼亚州居民隐私声明",
        "Information We Collect":"我们收集的信息",
        "Category":"分类",
        "Examples":"示例",
        "Collected":"收集",
        "YES":"是",
        "NO":"否",
        "Use of Personal Information":"个人信息的使用",
        "Sharing Personal Information":"共享个人信息",
        "Disclosures of Personal Information for a Business Purpose":"出于商业目的披露个人信息",
        "Sales of Personal Information":"出售个人信息",
        "Your Rights and Choices":"您的权利和选择",
        "Access to Specific Information and Data Portability Rights":"访问特定信息和数据可移植性权",
        "Deletion Request Rights":"删除请求权",
        "Exercising Access, Data Portability, and Deletion Rights":"行使访问权、数据可移植性和删除权",
        "Response Timing and Format":"响应时间和格式",
        "Non-Discrimination":"无歧视",
        "Changes to Our Privacy Notice":"隐私声明的变更",
        "Contact Information":"联系信息",
        "Effective Date:":"生效日期：",
        "Last reviewed on:":"最后审查日期：",
        "Do you have to enroll in the monetization program to get money?":"您必须加入变现计划才能赚钱吗？",
        "What methods can I use withdraw money from my account? Are there any fees?":"我可以使用哪些方法从我的账户中取款？是否有任何费用？",
        "How do I know Modrinth is being transparent about revenue?":"我如何知道 Modrinth 在收入方面是透明的？",
        "Date":"日期",
        "Creator Revenue (75%)":"创作者收益 （75%）",
        "Modrinth's Cut (25%)":"Modrinth 分成 (25%)",
        "Timeline":"时间线",
        "Reporting a Vulnerability":"报告漏洞",
        "Scope":"范围",
        "Copyright Policy":"版权政策",
        "Reporting Claims of Copyright Infringement":"报告版权侵权声明",
        "Counter Notification Procedures":"反通知处理流程",
        "Repeat Infringers":"重复侵权者",
        "You don't have any unread notifications.":"您没有任何未读通知。",
        "View history":"查看历史",
        "Notification history":"通知历史",
        "History":"历史记录",
        "Project updates":"项目更新",
        "Status changes":"状态更改",
        "Moderator messages":"版主消息",
        "Reports":"报告",
        "You don't have any active reports.":"您没有任何活动报告。",
        "Make an organization!":"创建一个组织！",
        "Create organization":"创建组织",
        "Followed projects":"关注的项目",
        "Create new":"新建",
        "Project updated":"项目已更新",
        "Your project has been updated.":"您的项目已经更新",
        "Moderation":"审核",
        "Project status":"项目状态",
        "Modrinth's team of content moderators work hard to review all submitted projects. Typically, you can expect a new project to be reviewed within 24 to 48 hours. Please keep in mind that larger projects, especially modpacks, may require more time to review. Certain holidays or events may also lead to delays depending on moderator availability. Modrinth's moderators will leave a message below if they have any questions or concerns for you.":"Modrinth 的内容审核员团队努力审查所有提交的项目。通常，您可以在 24 到 48 小时内审核新项目。请记住，较大的项目，尤其是整合包，可能需要更多时间来审核。某些节假日或活动也可能导致延迟，具体取决于版主。如果 Modrinth 的版主对您有任何问题或疑虑，他们会在下面留言。",
        "Current visibility":"当前可见性",
        "Not listed in search results":"未在搜索结果中列出",
        "Not listed on the profiles of members":"未在成员个人资料中列出",
        "Not accessible with a direct link":"无法通过直接链接访问",
        "Messages":"消息",
        "This is a private conversation thread with the Modrinth moderators. They may message you with issues concerning this project. This thread is only checked when you submit your project for review. For additional inquiries, contact":"这是与 Modrinth 版主的私人对话线程。他们可能会向您发送有关此项目的问题的消息。只有在您提交项目以供审核时，才会选中此线程。如有其他疑问，请联系 ",
        "Insufficient Description":"描述不足",
        "If your review has taken more than 48 hours, check our":"如果你的审核超过了 48 小时，请查看我们的",
        "for moderation delays.":"以了解审核延迟的情况。",
        "support article on review times":"关于审核时间的支持文章",
        "submitted the project for review.":"提交了项目进行审核。",
        "changed the project's status from":" 改变项目的状态从",
        "to":"到",
        "Reply to thread...":"回复线程...",
        "Reply to thread...":"回复线程...",
        "Open in new tab":"在新标签页中打开",
        "Copy link":"复制链接",


        "Discover content": "发现内容",
        "Host a server": "托管服务器",
        "Modrinth App": "Modrinth 应用",
        "New project": "新建项目",
        "New collection": "新建收藏夹",
        "New organization": "新建组织",
        "The place for Minecraft mods plugins data packs shaders resource packs modpacks":
        "Minecraft 模组、插件、数据包、光影包、资源包和整合包的家园",
        "Discover, play, and share Minecraft content through our open-source platform built for the community.":
        "通过我们为社区构建的开源平台发现、游玩和分享 Minecraft 内容。",
        Mods: "模组",
        Mod: "模组",
        mods: "模组",
        Plugins: "插件",
        Plugin: "插件",
        plugins: "插件",
        "Data Packs": "数据包",
        "data packs": "数据包",
        Shaders: "光影包",
        Shader: "光影包",
        shaders: "光影包",
        "resource packs": "资源包",
        "Resource Packs": "资源包",
        Modpacks: "整合包",
        Modpack: "整合包",
        modpacks: "整合包",
        Servers: "服务器",
        servers: "服务器",
        "Upgrade to Modrinth+": "升级到 Modrinth+",
        "Saved projects": "保存的项目",
        "My servers": "我的服务器",
        Notifications: "通知",
        Revenue: "收入",
        Analytics: "分析",
        "Sign out": "登出",
        "Discover, play, and share Minecraft content through our open-source platform built for the community.":
        "通过我们为社区打造的开源平台发现、游玩和分享 Minecraft 内容。",
        "Discover mods": "发现模组",
        "Go to dashboard": "前往仪表盘",
        "For Players": "面向玩家",
        "Discover over 50,000 creations": "发现超过 50,000 个创作",
        "From magical biomes to cursed dungeons, you can be sure to find content to bring your gameplay to the next level.":
        "从魔法生物群系到诅咒的地牢，你肯定能找到能提升游戏体验的内容。",
        "Find what you want, quickly and easily": "快速轻松地找到你想找的内容",
        "Modrinth's lightning-fast search and powerful filters let you find what you want as you type.":
        "Modrinth 的超快搜索和强大的筛选功能让你在输入时就能找到想要的内容。",
        "View:": "显示:",
        "List view": "列表视图",
        "Grid view": "网格视图",
        "Gallery view": "画廊视图",
        "Sort by:": "排序:",
        Relevance: "相关性",
        Downloads: "下载量",
        Follows: "关注数",
        "Date updated": "更新时间",
        "Date published": "发布时间",
        "Follow projects you love": "关注你喜欢的项目",
        "Get notified every time your favorite projects update and stay in the loop":
        "每次你关注的项目更新时都会收到通知，不错过任何动态",
        "Give an online home to your creations and reach a massive audience of dedicated players":
        "为你创作的内容提供在线家园，并触及大量忠实玩家",
        "Play with your favorite launcher": "使用你喜爱的启动器游玩",
        "Modrinth's open-source API lets launchers add deep integration with Modrinth. You can use Modrinth through":
        "Modrinth 的开源 API 让启动器能够深度集成 Modrinth。你可以通过",
        "our own app": "我们自己的应用程序",
        "and some of the most popular launchers like ATLauncher, MultiMC, and Prism Launcher.":
        "和一些最受欢迎的启动器(如 ATLauncher、MultiMC 和 Prism Launcher)使用 Modrinth。",
        "For Creators": "创作者专区",
        "Share your content with the world": "与世界分享你的内容",
        "Give an online home to your creations and reach a massive audience of dedicated players":
        "为你创作的内容提供在线家园，并触及大量忠实玩家",
        Discovery: "发现",
        "Get your project discovered by thousands of users through search, our home page, Discord server, and more ways to come in the future!":
        "通过搜索、我们的首页、Discord 服务器以及未来更多方式，让你的项目被成千上万的用户发现！",
        "Team Management": "团队管理",
        "Invite your teammates and manage roles and permissions with ease":
        "轻松邀请队友并管理角色和权限",
        Monetization: " 收益",
        "Get paid ad revenue from your project pages and withdraw your funds at any time":
        "从你的项目页面获得广告收入，并随时提现",
        "Diverse Ecosystem": "多样化的生态系统",
        "Integrate with your build tools through Minotaur for automatic uploads right when you release a new version":
        "通过 Minotaur 与构建工具集成，实现在发布新版本时自动上传",
        "Data and Statistics": "数据和统计",
        "Get detailed reports on page views, download counts, and revenue":
        "获取详细的页面浏览量、下载次数和收入报告",
        "Constantly Evolving": "不断进化",
        "Get the best modding experience possible with constant updates from the Modrinth team":
        "通过 Modrinth 团队的持续更新，获得最佳的模组制作体验",
        "Read more about": "了解更多关于",
        "Visit the blog": "访问博客",
        "Modrinth is ": "Modrinth 是 ",
        "open source": "开源的",
        ".": "。",
        Company: "公司",
        Terms: "条款",
        Privacy: "隐私",
        Rules: "规则",
        Careers: "职位",
        Resources: "资源",
        Support: "支持",
        About: "关于",
        Blog: "博客",
        Docs: "文档",
        Status: "状态",
        "Rewards Program": "奖励计划",
        Products: "产品",
        "Modrinth Servers": "Modrinth 服务器",
        "Help Center": "帮助中心",
        Translate: "翻译",
        "Report issues": "报告问题",
        "View source": "查看源代码",
        "Visit wiki": "访问Wiki",
        "Join Discord server": "加入Discord服务器",
        "Donate on Ko-fi": "在Ko-fi上捐赠",
        "Donate on Patreon": "在Patreon上捐赠",
        "Donate on PayPal": "在PayPal上捐赠",
        "Sponsor on GitHub": "GitHub上的赞助商",
        "API documentation": "API 文档",
        Legal: "法律",
        "Content Rules": "内容规则",
        "Terms of Use": "使用条款",
        "Security Notice": "安全声明",
        Interact: "互动",
        "X (Twitter)": "X (推特)",
        "Get Modrinth App": "获取 Modrinth 应用",
        "Sign in": "登录",
        "Sign up": "注册",
        "Sign in with": "使用以下方式登录",
        "Or use a password": "或使用密码",
        "Create an account": "创建账户",
        "Enter two-factor code": "输入两步验证码",
        "Please enter a two-factor code to proceed.": "请输入两步验证码以继续。",
        "Change theme": "更改主题",
        "NOT AN OFFICIAL MINECRAFT SERVICE. NOT APPROVED BY OR ASSOCIATED WITH MOJANG OR MICROSOFT.":
        "这不是官方的 Minecraft 服务。未经 Mojang 或 Microsoft 批准或关联。",
        "Join the conversation": "加入讨论",
        "Loading...": "加载中...",
        "No results found": "未找到结果",
        Home: "首页",
        Login: "登录",
        Register: "注册",
        Profile: "个人资料",
        Settings: "设置",
        Logout: "登出",
        Dashboard: "仪表盘",
        "My Projects": "我的项目",
        "My Organizations": "我的组织",
        "My Collections": "我的收藏夹",
        "Create Project": "创建项目",
        "Create Collection": "创建收藏夹",
        "Create Organization": "创建组织",
        "Latest News": "最新新闻",
        Featured: "精选",
        "Support us": "支持我们",
        "Help & Support": "帮助和支持",
        Documentation: "文档",
        "Terms of Service": "服务条款",
        "Privacy Policy": "隐私政策",
        Categories: "分类",
        Features: "特点",
        Trending: "趋势",
        "Featured Packs": "精选包",
        "Recent Activity": "最近活动",
        Community: "社区",
        Popular: "流行",
        "Search results for": "搜索结果",
        Submit: "提交",
        Apply: "应用",
        Cancel: "取消",
        Username: "用户名",
        Password: "密码",
        "Confirm Password": "确认密码",
        "Submit your mod": "提交你的模组",
        "Edit Project": "编辑项目",
        "Delete Project": "删除项目",
        "Project Settings": "项目设置",
        "Manage Organization": "管理组织",
        "Your Projects": "你的项目",
        "Your Collections": "你的收藏夹",
        "Your Organizations": "你的组织",
        "Add New Mod": "添加新模组",
        "Add New Collection": "添加新收藏夹",
        "Add New Organization": "添加新组织",
        "Minecraft Version": "Minecraft 版本",
        "Game Version": "游戏版本",
        "Game versions": "游戏版本",
        "Choose File": "选择文件",
        Upload: "上传",
        Download: "下载",
        "Install Instructions": "安装说明",
        "Change Log": "更新日志",
        Links: "链接",
        Creators: "作者",
        Details: "详情",
        "Report an Issue": "报告问题",
        "View Project": "查看项目",
        "Version History": "版本历史",
        "Modrinth API": "Modrinth API",
        "About Us": "关于我们",
        Contact: "联系方式",
        Support: "支持",
        "API Documentation": "API 文档",
        "Privacy Settings": "隐私设置",
        "Invite a member": "邀请成员",
        "Manage Members": "管理成员",
        "Organization Settings": "组织设置",
        "Request Access": "请求访问",
        "Create New Project": "创建新项目",
        "Project Version": "项目版本",
        Resources: "资源",
        "Installation Instructions": "安装说明",
        "Review and Ratings": "评论与评分",
        "View Comments": "查看评论",
        "Add Comment": "添加评论",
        "Add Review": "添加评分",
        Approve: "批准",
        Reject: "拒绝",
        Draft: "草稿",
        Publish: "发布",
        Published: "已发布",
        Unpublished: "未发布",
        Starred: "收藏",
        Favorites: "收藏夹",
        "User Reviews": "用户评论",
        Organization: "团队",
        Developer: "开发者",
        Owner: "所有者",
        "Created by": "创建者",
        "Version Notes": "版本说明",
        "Mods and Add-ons": "模组和附加组件",
        Contribute: "贡献",
        Donate: "捐赠",
        "Download Now": "立即下载",
        "Latest Release": "最新版本",
        "Upcoming Updates": "即将更新",
        "Install Now": "立即安装",
        Required: "必需",
        Optional: "可选",
        "Add to Favorites": "加入收藏夹",
        "View Details": "查看详情",
        "Related Projects": "相关项目",
        "Related Mods": "相关模组",
        "View All": "查看所有",
        New: "新建",
        Version: "版本",
        Versions: "版本",
        "Link to this page": "链接到此页面",
        "Copy Link": "复制链接",
        Share: "分享",
        "View More": "查看更多",
        Back: "返回",
        "Go Back": "返回",
        Continue: "继续",
        Next: "下一步",
        Previous: "上一页",
        "Cancel Subscription": "取消订阅",
        "Manage Subscription": "管理订阅",
        "Subscribe Now": "立即订阅",
        "Notifications Settings": "通知设置",
        Activate: "激活",
        Deactivate: "停用",
        "Terms and Conditions": "条款与条件",
        "Cookies Policy": "Cookies 政策",
        "Privacy Preferences": "隐私偏好设置",
        "User Agreement": "用户协议",
        "Sign In": "登录",
        "Sign Up": "注册",
        "Forgot Password?": "忘记密码？",
        "Reset Password": "重置密码",
        "Change Email": "更改邮箱",
        "Change Username": "更改用户名",
        "Update Profile": "更新个人资料",
        "Account Settings": "账户设置",
        "Security Settings": "安全设置",
        "Two-factor Authentication": "两步验证",
        "Security Questions": "安全问题",
        "Session Expired": "会话过期",
        "Account Suspended": "账户被暂停",
        "Subscription Expired": "订阅已过期",
        "Confirm Email Address": "确认电子邮件地址",
        "Email Verified": "邮箱已验证",
        Error: "错误",
        Success: "成功",
        Warning: "警告",
        Information: "信息",
        Confirmation: "确认",
        "Action Required": "需要操作",
        Retry: "重试",
        Save: "保存",
        Edit: "编辑",
        Delete: "删除",
        Close: "关闭",
        Description: "描述",
        Tags: "标签",
        Comments: "评论",
        Reviews: "评价",
        Rating: "评分",
        Stars: "星标",
        Members: "成员",
        Projects: "项目",
        Collections: "收藏夹",
        Organizations: "组织",
        Followers: "关注者",
        Following: "正在关注",
        Follow: "关注",
        Unfollow: "取消关注",
        Joined: "加入日期",
        "Last Updated": "最后更新",
        License: "许可证",
        Permissions: "权限",
        Collaborators: "协作者",
        Admin: "管理员",
        Moderator: "版主",
        Member: "成员",
        Guest: "访客",
        Public: "公开",
        Private: "私有",
        Team: "团队",
        Role: "角色",
        Actions: "操作",
        Select: "选择",
        Filter: "筛选",
        Clear: "清除",
        All: "全部",
        Active: "活跃",
        Inactive: "不活跃",
        Online: "在线",
        Offline: "离线",
        Verified: "已验证",
        Pending: "待处理",
        Rejected: "已拒绝",
        Approved: "已批准",
        Blocked: "已阻止",
        Banned: "已封禁",
        Suspended: "已暂停",
        Disabled: "已禁用",
        Enabled: "已启用",
        Visible: "可见",
        Hidden: "隐藏",
        Open: "打开",
        Closed: "关闭",
        Locked: "锁定",
        Unlocked: "解锁",
        Allowed: "允许",
        Forbidden: "禁止",
        Granted: "授予",
        Revoked: "撤销",
        Assigned: "分配",
        Unassigned: "未分配",
        Available: "可用",
        Unavailable: "不可用",
        Installed: "已安装",
        "Not Installed": "未安装",
        Compatible: "兼容",
        Incompatible: "不兼容",
        Supported: "支持",
        Unsupported: "不支持",
        "Required Files": "必需文件",
        "Recommended Files": "推荐文件",
        "Optional Files": "可选文件",
        Dependencies: "依赖项",
        Conflict: "冲突",
        Changelog: "更新日志",
        Gallery: "画廊",
        Channels: "渠道",
        Compatibility: "兼容版本",
        Platforms: "平台",
        "Supported environments": "运行环境",
        "Client-side": "客户端",
        "Server-side": "服务端",
        "Read more": "阅读更多",
        "See all": "查看全部",
        "Load more": "加载更多",
        Exclude: "排除",
        "More options": "更多选项",
        Report: "举报",
        "Copy ID": "复制ID",
        "Copy permanent link": "复制永久链接",
        //Mods页面补全
        "75% of ad revenue goes to creators": "75% 的广告收入归创作者所有",
        "Support creators and Modrinth ad-free with ":
        "通过 Modrinth+ 无广告地支持创作者和 ",
        "Game version": "游戏版本",
        "Search...": "搜索...",
        "Search mods...": "搜索模组...",
        "Search resource packs..": "搜索资源包...",
        "Search data packs...": "搜索数据包...",
        "Search shaders...": "搜索光影包...",
        "Search modpacks...": "搜索整合包...",
        "Search plugins...": "搜索插件...",
        "Show all versions": "显示所有版本",
        Loader: "加载器",
        "Show more": "显示更多",
        "Show fewer": "显示更少",
        Adventure: "冒险",
        Cursed: "诅咒",
        Decoration: "装饰",
        Economy: "经济",
        Equipment: "装备",
        Food: "食物",
        "Game Mechanics": "游戏机制",
        Library: "库",
        Magic: "魔法",
        Management: "管理",
        Minigame: "小游戏",
        Mobs: "生物",
        Optimization: "优化",
        Social: "社交",
        Storage: "存储",
        Technology: "科技",
        Transportation: "运输",
        Utility: "实用工具",
        "World Generation": "世界生成",
        Environment: "环境",
        "Client or server": "客户端或服务端",
        "Client and server": "客户端和服务端",
        Client: "客户端",
        Server: "服务端",
        "Open source": "开源",
        //资源包页面补全
        Combat: "战斗",
        Modded: "修改",
        Realistic: "现实",
        Simplistic: "简洁",
        Themed: "主题",
        Tweaks: "调整",
        "Vanilla-like": "原版风格",
        Audio: "音频",
        Blocks: "方块",
        "Core Shaders": "核心光影",
        Entities: "实体",
        Fonts: "字体",
        Items: "物品",
        Locale: "本地化",
        Models: "模型",
        Resolutions: "分辨率",
        "8x or lower": "8x或更低",
        "512x or higher": "512x或更高",
        //光影包页面补全
        Cartoon: "卡通",
        Fantasy: "幻想",
        "Semi-realistic": "半现实",
        Atmosphere: "大气效果",
        Bloom: "光晕",
        "Colored Lighting": "彩色光照",
        Foliage: "植被",
        "Path Tracing": "路径追踪",
        Reflections: "反射",
        Shadows: "阴影",
        "Performance impact": "性能影响",
        High: "高",
        Low: "低",
        Medium: "中",
        Potato: "土豆",
        Screenshot: "截图",
        //整合包页面补全
        Challenging: "硬核",
        "Kitchen Sink": "水槽",
        Lightweight: "轻量",
        Multiplayer: "多人",
        Quests: "任务",
        //插件页面补全
        Platfrom: "平台",
        //设置页面补全
        Display: "显示",
        Appearance: "外观",
        "Color theme": "颜色主题",
        "Select your preferred color theme for Modrinth on this device.":
        "在此设备上为 Modrinth 选择您喜欢的颜色主题。",
        "Sync with system": "与系统同步",
        Light: "浅色",
        Dark: "深色",
        "Project list layouts": "项目列表布局",
        "Select your preferred layout for each page that displays project lists on this device.":
        "为该设备上显示项目列表的每个页面选择您喜欢的布局。",
        Rows: "列表",
        Grid: "网格",
        "Mods page": "模组页面",
        "Plugins page": "插件页面",
        "Data Packs page": "数据包页面",
        "Shaders page": "光影包页面",
        "Resource Packs page": "资源包页面",
        "Modpacks page": "整合包页面",
        "User profile pages": "用户个人资料页面",
        "Toggle features": "切换功能",
        "Advanced rendering": "高级渲染",
        "Open external links in new tab": "在新标签页中打开外部链接",
        "Right-aligned filters sidebar on search pages":
        "搜索页面上右对齐的过滤器侧边栏",
        "Left-aligned sidebar on content pages": "内容页左对齐侧边栏",
        "Enable or disable certain features on this device.":
        "启用或禁用此设备上的某些功能。",
        "Enables advanced rendering such as blur effects that may cause performance issues without hardware-accelerated rendering.":
        "启用高级渲染（例如模糊效果），如果没有硬件加速渲染，可能会导致性能问题。",
        "Make links which go outside of Modrinth open in a new tab. No matter this setting, links on the same domain and in Markdown descriptions will open in the same tab, and links on ads and edit pages will open in a new tab.":
        "让 Modrinth 之外的链接在新标签页中打开。无论此设置如何，同一域名和 Markdown 描述中的链接都会在同一个标​​签页中打开，而广告和编辑页面上的链接则会在新标签页中打开。",
        "Aligns the filters sidebar to the right of the search results.":
        "将过滤器侧边栏与搜索结果的右侧对齐。",
        "Aligns the sidebar to the left of the page's content.":
        "将侧边栏与页面内容左侧对齐。",
        "Manage projects": "管理项目",
        Account: "账户",
        "Public profile": "公开资料",
        "Profile information": "个人资料信息",
        "Your profile information is publicly viewable on Modrinth and through the Modrinth API。":
        "您的个人资料信息可在 Modrinth 上以及通过 Modrinth API 公开查看。",
        "Profile picture": "个人资料头像",
        "Upload image": "上传图片",
        "Remove image": "删除图片",
        "A unique case-insensitive name to identify your profile.":
        "一个不区分大小写的唯一名称，用于标识您的个人资料。",
        Bio: "简介",
        "A short description to tell everyone a little bit about you.":
        "简短的描述，让大家稍微了解一下您。",
        "Changes saved": "保存更改",
        "Account and security": "账户与安全",
        "Account security": "账户安全",
        Email: "电子邮件",
        "Change email": "修改电子邮件",
        "Email address": "电子邮件地址",
        "Enter Your Email Address...": "输入您的电子邮件地址...",
        "Save email": "保存电子邮件",
        "Add password": "添加密码",
        "Save password": "保存密码",
        "Two-factor authentication": "2FA验证",
        "Setup two-factor authentication": "设置2FA验证",
        "Setup 2FA": "设置2FA",
        "Manage authentication providers": "管理身份验证提供程序",
        "Authentication providers": "身份验证提供程序",
        "Manage providers": "管理提供程序",
        Provider: "提供程序",
        Add: "添加",
        Remove: "删除",
        "Data export": "数据导出",
        "Generate export": "生成导出",
        "Delete account": "删除账户",
        "Changes the email associated with your account.":
        "更改与您的帐户关联的电子邮件。",
        "Your account information is not displayed publicly.":
        "您的帐户信息不会公开显示。",
        "Set a permanent password to login to your account.":
        "设置永久密码以登录您的帐户。",
        "New password": "新密码",
        "Confirm new password": "确认新密码",
        "Add an additional layer of security to your account during login.":
        "在登录期间为您的帐户添加额外的安全层。",
        "Two-factor authentication keeps your account secure by requiring access to a second device in order to sign in.":
        "2FA验证要求访问第二台设备才能登录，从而确保您的帐户安全。",
        "Scan the QR code with Authy, Microsoft Authenticator, or any other 2FA app to begin.":
        "使用 Authy 、 Microsoft Authenticator 或任何其他 2FA 应用扫描二维码即可开始。",
        "If the QR code does not scan, you can manually enter the secret:":
        "如果二维码扫描不出来，可以手动输入密码：",
        "Add or remove sign-on methods from your account, including GitHub, GitLab, Microsoft, Discord, Steam, and Google.":
        "从您的帐户中添加或删除登录方法，包括 GitHub、GitLab、Microsoft、Discord、Steam 和 Google。",
        "Request a copy of all your personal data you have uploaded to Modrinth. This may take several minutes to complete.":
        "请求获取您已上传至 Modrinth 的所有个人数据的副本。这可能需要几分钟才能完成。",
        "Once you delete your account, there is no going back. Deleting your account will remove all attached data, excluding projects, from our servers.":
        "帐户一旦删除，将无法恢复。删除帐户将从我们的服务器中删除所有附加数据（项目除外）。",
        "Authorized apps": "授权应用",
        "You have not authorized any applications.": "您尚未授权任何应用程序。",
        "When you authorize an application with your Modrinth account, you grant it access to your account. You can manage and review access to your account here at any time.":
        "当您使用 Modrinth 帐户授权某个应用程序时，即表示您授予该应用程序访问您帐户的权限。您可以随时在此管理和查看您帐户的访问权限。",
        Sessions: "会话",
        "Here are all the devices that are currently logged in with your Modrinth account. You can log out of each one individually.":
        "以下是当前已使用您的 Modrinth 帐户登录的所有设备。您可以单独退出每个设备。",
        "If you see an entry you don't recognize, log out of that device and change your Modrinth account password immediately.":
        "如果您看到不认识的条目，请立即退出该设备并更改您的 Modrinth 帐户密码。",
        "Billing and subscriptions": "计费和订阅",
        Subscriptions: "订阅",
        "Manage your Modrinth subscriptions.": "管理您的 Modrinth 订阅",
        "Payment methods": "付款方式",
        "Add payment method": "添加付款方式",
        "View past charges": "查看过去的费用",
        "You have not added any payment methods.": "您尚未添加任何付款方式。",
        "Personal access tokens": "个人访问令牌",
        "Create a PAT": "创建PAT",
        "PATs can be used to access Modrinth's API. For more information, see Modrinth's API documentation. They can be created and revoked at any time.":
        "PAT 可用于访问 Modrinth 的 API。更多信息，请参阅 Modrinth 的 API 文档 。PAT 可以随时创建和撤销。",
        "Your applications": "您的应用程序",
        "New Application": " 新申请",
        "Applications can be used to authenticate Modrinth's users with your products. For more information, see Modrinth's API documentation.":
        "应用程序可用于通过您的产品对 Modrinth 的用户进行身份验证。有关更多信息，请参阅 Modrinth 的 API 文档 。",

        //仪表板补全
        Overview: "概述",
        "Active reports": "活动报告",
        Manage: "管理",
        "Visit your profile": "访问您的个人资料",
        "You have no unread notifications.": "您没有未读通知。",
        "View notification history": "查看历史消息记录",
        "Total downloads": "总下载量",
        "Total followers": "总关注量",

        // 遍历页面内容并替换为翻译
    };

    // 遍历页面内容并替换为翻译
    const translateText = (node) => {
        if (node.nodeType === Node.TEXT_NODE) {
            const originalText = node.textContent.trim();
            if (translations[originalText]) {
                node.textContent = translations[originalText];
            }
        } else if (node.nodeType === Node.ELEMENT_NODE) {
            // 处理 placeholder 属性
            if (node.hasAttribute("placeholder")) {
                const originalPlaceholder = node.getAttribute("placeholder").trim();
                if (translations[originalPlaceholder]) {
                    node.setAttribute("placeholder", translations[originalPlaceholder]);
                }
            }
            // 继续遍历子节点
            for (let child of node.childNodes) {
                translateText(child);
            }
        }
    };

    // 页面加载后开始翻译
    const observer = new MutationObserver(() => {
        translateText(document.body);
    });

    observer.observe(document.body, {
        childList: true,
        subtree: true,
    });

    // 初次加载时立即翻译
    translateText(document.body);
})();
